#!/bin/bash
#author kissyouhunter

declare flag=0
clear
while [ "$flag" -eq 0 ]
do

TIME() {
[[ -z "$1" ]] && {
	echo -ne " "
} || {
     case $1 in
	r) export Color="\e[31;1m";;
	g) export Color="\e[32;1m";;
	b) export Color="\e[34;1m";;
	y) export Color="\e[33;1m";;
	z) export Color="\e[35;1m";;
	l) export Color="\e[36;1m";;
      esac
	[[ $# -lt 2 ]] && echo -e "\e[36m\e[0m ${1}" || {
		echo -e "\e[36m\e[0m ${Color}${2}\e[0m"
	 }
      }
}

TIME g "============================================"
TIME g "       欢迎使用N1——openwrt更新脚本"
TIME g "          请确认N1可以科学上网"
TIME g "          根据提示输入对应数值 "
TIME g "============================================"

TIME b "(1) G胸 N1 固件!"
TIME z "(2) K胸 N1 固件!"
TIME l "(0) 怂了，不更新了！"

read -p "Please enter your choice[0-2]: " input
case $input in
#G胸 N1 固件
1)
clear
TIME g " >>>>>>>>>>>跳转中，请稍等 ......"
bash <(curl -Lso- https://git.io/Phicomm-n1_update)
;;
#K胸 N1 固件
2)
clear
TIME g " >>>>>>>>>>>跳转中，请稍等 ......"
bash <(curl -s -S -L https://git.io/update-N1)
;;
0)
clear
exit 0
;;
*)  TIME r "----------------------------------"
 TIME r "|          Warning!!!            |"
 TIME r "|       请输入正确的选项!        |"
 TIME r "----------------------------------"
 for i in `seq -w 3 -1 1`
   do
     TIME r "$i";
     sleep 1;
   done
 clear
;;
esac
done
