#!/bin/bash

TIME() {
[[ -z "$1" ]] && {
  echo -ne " "
} || {
     case $1 in
  r) export Color="\e[31;1m";;
  g) export Color="\e[32;1m";;
  b) export Color="\e[34;1m";;
  y) export Color="\e[33;0m";;
  z) export Color="\e[35;1m";;
  l) export Color="\e[36;1m";;
      esac
  [[ $# -lt 2 ]] && echo -e "\e[36m\e[0m ${1}" || {
    echo -e "\e[36m\e[0m ${Color}${2}\e[0m"
   }
      }
}

while :; do
echo
TIME g "--- N1固件 在线更新菜单 ----"
echo
TIME g "[1] 更新  kiss 编译的 N1固件"
echo
TIME g "[2] 更新 gd772 编译的 N1固件"
echo
TIME r "[0] 继续做 钉子户 退出更新!"
TIME g "----------------------------"
read -p " 请输入 序号 敲回车确认： " CHOOSE
case $CHOOSE in
2)
echo
TIME g "检查 设备网络状态中..."
curl --connect-timeout 8 -o /tmp/google.html -s -w %{time_namelookup}: https://www.google.com > /dev/null 2>&1
if [[ -f /tmp/google.html ]] && [[ $(grep -c "Google" /tmp/google.html) -ge '1' ]]; then
  rm -rf /tmp/google.html
  echo
  TIME y "设备网络状态正常！正在加载 更新菜单"
else
  echo
  TIME "您的设备 科学上网状态异常！无法加载 固件升级菜单 请自行检查 网设环境设置"
  echo "您的设备 科学上网状态异常！无法加载 固件升级菜单 请自行检查 网设环境设置" > /tmp/cloud_version
  echo
  exit 1
fi

bash <(curl -Lso- http://drive.gd772.net/d/update/AutoUpdate.sh)  
  
break
;;
1)
echo
TIME g "检查p4分区剩余空间..."
volume=$(df -m | grep /dev/mmcblk2p4 | grep -v docker | awk '{print $4}')
if [ $volume -ge 1024 ]; then
  TIME y "p4分区空间足够，继续运行脚本"
  echo
else
  TIME r "p4分区为${volume}m，小于1G。删除垃圾文件后再运行更新命令"
  exit 0
fi
TIME g "正在检查 科学上网状态..."
curl --connect-timeout 8 -o /tmp/google.html -s -w %{time_namelookup}: http://www.google.com > /dev/null 2>&1
if [[ -f /tmp/google.html ]] && [[ $(grep -c "google" /tmp/google.html) -ge '1' ]]; then
  rm -rf /tmp/google.html
  echo
  TIME y "设备网络状态正常！正在加载 更新菜单"
else
  echo
  TIME "您的设备 不能科学上网！ 无法加载固件升级菜单 请自行检查设备网络环境 是否能科学上网"
  echo "您的设备 不能科学上网！ 无法加载固件升级菜单 请自行检查设备网络环境 是否能科学上网" > /tmp/cloud_version
  echo
  exit 1
fi
bash <(curl -Lso- http://cloud.kisslove.eu.org/d/aliyun/files/update-N1.sh)
break
;;
0)
echo
TIME r "[0] 继续做 钉子户 退出本次更新"
echo
exit 0
break
;;
*)
echo
TIME r "请输入正确的序号!"
;;
esac
done
